# https://github.com/ether/etherpad-lite

name: Docker build Etherpad ARM image

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "::set-output name=commit::$(git ls-remote git://github.com/ether/etherpad-lite.git | head -n1 | awk '{print $1;}')"
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: etherpad
          key: ${{ runner.os }}-v1-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Check Out Repo
        uses: actions/checkout@v2
          
      - name: Check Out Repo ether/etherpad-lite
        uses: actions/checkout@v2
        with:
          repository: "ether/etherpad-lite"
          ref: 'master'
          path: 'etherpad-git'
      
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Set up build timestamp
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push acme
        id: docker_build_new_custom
        uses: docker/build-push-action@v2
        with:
          context: ./etherpad-git/
          file: ./etherpad-git/Dockerfile
          platforms: linux/arm64
          push: true
          tags: vimarsh244/arm-etherpad:latest, vimarsh244/arm-etherpad:build-${{ env.timestamp }}
