name: build docker for Focalboard

env:
  FOCALBOARD_MAJOR: 0
  FOCALBOARD_MINOR: 6
  FOCALBOARD_INCREMENT: 5

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - id: focalboard
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: mattermost/focalboard
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7,linux/arm64
          file: ./mattermost/focalboard//Dockerfile
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          build-args: FOCALBOARD_REF=${{ steps.focalboard.outputs.release }}
          tags: |
            vimarsh244/arm-focalboard:${{ steps.focalboard.outputs.release }}
            vimarsh244/arm-focalboard:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
