name: Build and Push Mattermost Docker Image to Docker Hub

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        # This step is essential for building ARM images on an AMD runner
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        # This sets up the advanced builder needed for multi-platform builds
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        # This uses your repository secrets to log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Sets the build context to the repository root
          context: .
          # Specifies the exact path to your Dockerfile
          file: ./mattermost/ee/Dockerfile
          # Defines the target platforms for the build
          platforms: linux/amd64,linux/arm64
          # Pushes the image only on merges/pushes to main, not on PRs
          push: ${{ github.event_name != 'pull_request' }}
          # Tags the image with your Docker Hub username and repo name
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mattermost-enterprise:latest
            ${{ secrets.DOCKER_USERNAME }}/mattermost-enterprise:9.8.0