name: Docker build outline images

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        id: cache
        with:
          path: mailcow
          key: ${{ runner.os }}-v1-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Check Out Repo
        uses: actions/checkout@v2
          
      - name: Check Out Repo outline/outline
        uses: actions/checkout@v2
        with:
          repository: "outline/outline"
          ref: 'main'
          path: 'outline-git'
      
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Set up build timestamp
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push outline
        id: docker_build_outline
        uses: docker/build-push-action@v2
        with:
          context: ./outline-git/
          file: ./outline-git/Dockerfile
          platforms: linux/arm64
          push: true
          tags: vimarsh244/arm-outline:latest, vimarsh244/arm-outline:build-${{ env.timestamp }}
